default: &defaults
  adapter: mysql
  username: burndown
  password: burndown
  encoding: utf8
  host: 127.0.0.1
  
development:
  database: burndown_development
  <<: *defaults

test:
  database: burndown_test
  <<: *defaults

production:
  database: burndown_production
#  database: burndown_development
  <<: *defaults
