# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'



task :foo do

  def ask(what, default = nil)
    print %Q{#{what}#{default.nil? ? '' : " [#{default}]"}> }
    x = STDIN.gets.chomp.strip
    x == '' ? (default.nil? ? ask(what) : default) : x
  end

  foo = ask 'type something in'
  puts "you said '#{foo}'"

end
