// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
var dashcodePartSpecs = {
    'helloText': { creationFunction: 'CreateText', text: 'Hallo!'  },
    'info': { creationFunction: 'CreateInfoButton', frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack'  },
    'done': { creationFunction: 'CreateGlassButton', text: 'Fertig', onclick: 'showFront'  },
    '***end***': {}
};
