// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
var dashcodePartSpecs = {
    'info': { creationFunction: 'CreateInfoButton', frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack'  },
    'done': { creationFunction: 'CreateGlassButton', onclick: 'showFront', text: 'Fertig' },
    'text': { creationFunction: 'CreateText', text: 'URL' },
    'text1': { creationFunction: 'CreateText', text: 'Projects' },
    'text2': { creationFunction: 'CreateText', text: 'Iterations' },
    '***end***': {}
};
